artifacts_root: artifacts

data_ingestion:
  root_directory: artifacts/data_ingestion
  source_URL: https://github.com/KR-16/Chicken-Disease-Classification-MLOPS/raw/main/Chicken-fecal-images.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_directory: artifacts/data_ingestion


prepare_base_model:
  root_directory: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/updated_base_model.h5